// Generated from the GHL 'County of Interest' picklist on 2026-09-02. Regenerate if the list changes in GHL.
export const COUNTY_OPTIONS = [
 "Calvert County - MD",
 "Charles County - MD",
 "St. Mary's County - MD",
 "Alamance County - NC",
 "Beaufort County - NC",
 "Bertie County - NC",
 "Bladen County - NC",
 "Brunswick County - NC",
 "Camden County - NC",
 "Carteret County - NC",
 "Caswell County - NC",
 "Chatham County - NC",
 "Chowan County - NC",
 "Columbus County - NC",
 "Craven County - NC",
 "Cumberland County - NC",
 "Currituck County - NC",
 "Dare County - NC",
 "Duplin County - NC",
 "Durham County - NC",
 "Edgecombe County - NC",
 "Franklin County - NC",
 "Gates County - NC",
 "Granville County - NC",
 "Greene County - NC",
 "Guilford County - NC",
 "Halifax County - NC",
 "Harnett County - NC",
 "Hertford County - NC",
 "Hoke County - NC",
 "Hyde County - NC",
 "Johnston County - NC",
 "Jones County - NC",
 "Lee County - NC",
 "Lenoir County - NC",
 "Martin County - NC",
 "Moore County - NC",
 "Nash County - NC",
 "New Hanover County - NC",
 "Northampton County - NC",
 "Onslow County - NC",
 "Orange County - NC",
 "Pamlico County - NC",
 "Pasquotank County - NC",
 "Pender County - NC",
 "Perquimans County - NC",
 "Person County - NC",
 "Pitt County - NC",
 "Randolph County - NC",
 "Robeson County - NC",
 "Sampson County - NC",
 "Scotland County - NC",
 "Tyrrell County - NC",
 "Vance County - NC",
 "Wake County - NC",
 "Warren County - NC",
 "Washington County - NC",
 "Wayne County - NC",
 "Wilson County - NC",
 "Dillon County - SC",
 "Horry County - SC",
 "Marion County - SC",
 "Marlboro County - SC",
 "Accomack County - VA",
 "Albemarle County - VA",
 "Amelia County - VA",
 "Amherst County - VA",
 "Appomattox County - VA",
 "Arlington County - VA",
 "Augusta County - VA",
 "Bedford County - VA",
 "Brunswick County - VA",
 "Buckingham County - VA",
 "Campbell County - VA",
 "Cape Charles - VA",
 "Caroline County - VA",
 "Charles City County - VA",
 "Charlotte County - VA",
 "Chesterfield County - VA",
 "City of Alexandria - VA",
 "City of Chesapeake - VA",
 "City of Fairfax - VA",
 "City of Franklin - VA",
 "City of Richmond - VA",
 "Clarke County - VA",
 "Culpeper County - VA",
 "Cumberland County - VA",
 "Dinwiddie County - VA",
 "Essex County - VA",
 "Fairfax County - VA",
 "Falls Church - VA",
 "Fauquier County - VA",
 "Fluvanna County - VA",
 "Franklin County - VA",
 "Frederick County - VA",
 "Fredericksburg - VA",
 "Gloucester County - VA",
 "Goochland County - VA",
 "Greene County - VA",
 "Greensville County - VA",
 "Halifax County - VA",
 "Hampton - VA",
 "Hanover County - VA",
 "Harrisonburg - VA",
 "Henrico County - VA",
 "Hopewell - VA",
 "Isle of Wight County - VA",
 "James City County - VA",
 "King and Queen County - VA",
 "King George County - VA",
 "King William County - VA",
 "Lancaster County - VA",
 "Loudoun County - VA",
 "Louisa County - VA",
 "Lunenburg County - VA",
 "Lynchburg - VA",
 "Madison County - VA",
 "Manassas - VA",
 "Manassas Park - VA",
 "Mathews County - VA",
 "Mecklenburg County - VA",
 "Middlesex County - VA",
 "Nelson County - VA",
 "New Kent County - VA",
 "Newport News - VA",
 "Norfolk - VA",
 "Northampton County - VA",
 "Northumberland County - VA",
 "Nottoway County - VA",
 "Orange County - VA",
 "Page County - VA",
 "Petersburg - VA",
 "Pittsylvania County - VA",
 "Poquoson - VA",
 "Portsmouth - VA",
 "Powhatan County - VA",
 "Prince Edward County - VA",
 "Prince George County - VA",
 "Prince William County - VA",
 "Rappahannock County - VA",
 "Richmond County - VA",
 "Rockingham County - VA",
 "Shenandoah County - VA",
 "Southampton County - VA",
 "Spotsylvania County - VA",
 "Stafford County - VA",
 "Staunton - VA",
 "Suffolk - VA",
 "Surry County - VA",
 "Sussex County - VA",
 "Virginia Beach - VA",
 "Warren County - VA",
 "Waynesboro - VA",
 "Westmoreland County - VA",
 "Williamsburg - VA",
 "Winchester - VA",
 "York County - VA"
];

const norm = (s) => String(s || '').toLowerCase().replace(/\b(county|city of|co\.?)\b/g, ' ').replace(/[^a-z ]/g, ' ').replace(/\s+/g, ' ').trim();

/** Best-effort match of free-text "county or city" input to a GHL picklist option. Returns null when unsure. */
export function matchCounty(input) {
  const q = norm(input);
  if (!q) return null;
  const stateHint = (String(input).match(/\b(VA|NC|SC|MD|virginia|north carolina|south carolina|maryland)\b/i) || [])[1];
  const stateMap = { virginia: 'VA', 'north carolina': 'NC', 'south carolina': 'SC', maryland: 'MD' };
  const st = stateHint ? (stateMap[stateHint.toLowerCase()] || stateHint.toUpperCase()) : null;
  const cands = COUNTY_OPTIONS.filter((o) => {
    const [name, state] = o.split(' - ');
    if (st && state !== st) return false;
    const n = norm(name);
    return n === q || n === q.replace(/\b(va|nc|sc|md)\b/g, '').trim();
  });
  if (cands.length === 1) return cands[0];
  // Same name in several states and no state given: prefer Virginia, but only if that is unambiguous.
  const va = cands.filter((c) => c.endsWith(' - VA'));
  return va.length === 1 ? va[0] : null;
}
